Narrowing the gap between the downstream and upstream operators.
ManageIQ/manageiq-pods pull request #675
Opened 2021-02-02 23:06 UTC by abellotti

Narrowing the gap between the downstream and upstream operators.

These changes are:
  - support optional image specifications via environment variables:
      HTTPD_IMAGE
      KAFKA_IMAGE
      ZOOKEEPER_IMAGE
      MEMCACHED_IMAGE
      BASEWORKER_IMAGE
      WEBSERVERWORKER_IMAGE
      UIWORKER_IMAGE
      ORCHESTRATOR_IMAGE
      POSTGRESQL_IMAGE

  - Memcached and Postgresql PodSpec define the default ServiceAccountName

2021-02-02 23:08 UTC, abellotti commented
Hi @bdunne, I found this set of change in the downstream operator that were added. They seem benign to bring back to upstream and help us minimizing the differences.  Let me know.  Thanks.

2021-02-02 23:12 UTC, Fryguy commented
Big :+1: from me for custom images!

2021-02-02 23:12 UTC, Fryguy commented
Can you update the PR title to reflect the actual change (and not the "why" you made the change)?

2021-02-02 23:26 UTC, Fryguy approved these changes

2021-02-05 20:48 UTC, bdunne requested changes
So, I'm 👍🏻 for bringing as much as possible to upstream, but  👎🏻 on this particular change.

What is the use case for this?  I see too many problems with using ENV vars:
- I could see users being extremely confused if they specify a value for images in the CR and then get something else when the operator creates the deployments. (because of an ENV var on the operator)
- I'd prefer to have a single place to specify the image names (CR).
- For example: If you want to update a single deployment (say httpd) in this scenario, you would have to edit the operator deployment which would bounce the operator pod which would then deploy the new httpd pod. Whereas, the CR could be edited and the operator would update the httpd deployment (no need to edit the operator deployment and bounce the operator pod).

2021-02-08 15:58 UTC, abellotti commented
Closing this, as it would only be needed in an installer and not the manageiq-operator.

2021-02-08 15:58 UTC, closed without merging